name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print current working dir
        run: |
          ls -la $PWD
          echo $PWD
          ls -la $GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE
          mkdir test && cd test/
          ls -la $PWD
          echo $PWD
          ls -la $GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE

          touch .config
          cat >> .config <<EOF
          CONFIG_TARGET_IMAGES_GZIP=y
          CONFIG_KERNEL_BUILD_USER="OpenWrt-CI"
          CONFIG_KERNEL_BUILD_DOMAIN="Azure"
          EOF
          cat .config
